name: Cypress Run
on: [push, pull_request]

defaults:
  run:
    working-directory: ./packages/frontend

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('package-lock.json') }}
          restore-keys: yarn-
      - run: yarn add @synthetixio/synpress
      - run: echo "CYPRESS_BASE_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
      - run: echo "SECRET_WORDS=${{ secrets.SECRET_WORDS }}" >> $GITHUB_ENV
      - run: echo "NETWORK_NAME=${{ secrets.NETWORK_NAME }}" >> $GITHUB_ENV
      - run: echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
      - run: yarn run build
      - run: yarn start
      - run: yarn run cypress:gh
